name: Build

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        clean: false
        submodules: 'recursive'
        token: ${{ secrets.MY_REPO_PAT }}
    - run: |
        git fetch --prune --unshallow --tags

      
    - uses: goreleaser/goreleaser-action@v5
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro':
        distribution: goreleaser
        version: latest
        args: release --clean --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.MY_REPO_PAT }}  
