name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        clean: false
        submodules: 'recursive'
        token: ${{ secrets.MY_REPO_PAT }}
    - run: |
        git fetch --prune --unshallow --tags

    - name: Get dependencies and build
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc-mingw-w64-x86-64
        sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        go build .

    - name: Upload binary files (linux_amd64)
      uses: actions/upload-artifact@v2
      with:
        name: stripe-handler_linux_amd64
        path: stripe-handler*
